// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aaljgkftxgldycpceywj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFhbGpna2Z0eGdsZHljcGNleXdqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA1NzIxMjksImV4cCI6MjA1NjE0ODEyOX0.DsV-JdnadzkscuIxR-yQwCkiA6GlZ8mlwwWbNkRxSUU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);